/*
SQLyog Ultimate v9.01 
MySQL - 5.5.16-log 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table  IF NOT EXISTS `wp_donations_countries` (
	`id` int (11),
	`name` varchar (255),
	`iso_2` varchar (6),
	`iso_3` varchar (9)
);
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('1','Antigua and Barbuda','AG','ATG');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('2','Algeria','DZ','DZA');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('3','Azerbaijan','AZ','AZE');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('4','Albania','AL','ALB');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('5','Armenia','AM','ARM');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('6','Angola','AO','AGO');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('7','American Samoa','AS','ASM');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('8','Argentina','AR','ARG');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('9','Australia','AU','AUS');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('10','Bahrain','BH','BHR');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('11','Barbados','BB','BRB');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('12','Bermuda','BM','BMU');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('13','Bahamas','BS','BHS');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('14','Bangladesh','BD','BGD');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('15','Belize','BZ','BLZ');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('16','Bosnia and Herzegovina','BA','BIH');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('17','Bolivia','BO','BOL');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('18','Burma','MM','MMR');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('19','Benin','BJ','BEN');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('20','Solomon Islands','SB','SLB');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('21','Brazil','BR','BRA');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('22','Bulgaria','BG','BGR');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('23','Brunei Darussalam','BN','BRN');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('24','Canada','CA','CAN');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('25','Cambodia','KH','KHM');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('26','Sri Lanka','LK','LKA');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('27','Congo','CG','COG');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('28','Democratic Republic of the Congo','CD','COD');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('29','Burundi','BI','BDI');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('30','China','CN','CHN');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('31','Afghanistan','AF','AFG');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('32','Bhutan','BT','BTN');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('33','Chile','CL','CHL');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('34','Cayman Islands','KY','CYM');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('35','Cameroon','CM','CMR');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('36','Chad','TD','TCD');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('37','Comoros','KM','COM');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('38','Colombia','CO','COL');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('39','Costa Rica','CR','CRI');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('40','Central African Republic','CF','CAF');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('41','Cuba','CU','CUB');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('42','Cape Verde','CV','CPV');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('43','Cook Islands','CK','COK');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('44','Cyprus','CY','CYP');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('45','Denmark','DK','DNK');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('46','Djibouti','DJ','DJI');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('47','Dominica','DM','DMA');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('48','Dominican Republic','DO','DOM');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('49','Ecuador','EC','ECU');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('50','Egypt','EG','EGY');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('51','Ireland','IE','IRL');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('52','Equatorial Guinea','GQ','GNQ');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('53','Estonia','EE','EST');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('54','Eritrea','ER','ERI');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('55','El Salvador','SV','SLV');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('56','Ethiopia','ET','ETH');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('57','Austria','AT','AUT');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('58','Czech Republic','CZ','CZE');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('59','French Guiana','GF','GUF');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('60','Finland','FI','FIN');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('61','Fiji','FJ','FJI');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('62','Falkland Islands (Malvinas)','FK','FLK');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('63','Micronesia, Federated States of','FM','FSM');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('64','French Polynesia','PF','PYF');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('65','France','FR','FRA');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('66','Gambia','GM','GMB');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('67','Gabon','GA','GAB');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('68','Georgia','GE','GEO');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('69','Ghana','GH','GHA');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('70','Grenada','GD','GRD');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('71','Greenland','GL','GRL');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('72','Germany','DE','DEU');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('73','Guam','GU','GUM');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('74','Greece','GR','GRC');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('75','Guatemala','GT','GTM');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('76','Guinea','GN','GIN');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('77','Guyana','GY','GUY');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('78','Haiti','HT','HTI');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('79','Honduras','HN','HND');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('80','Croatia','HR','HRV');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('81','Hungary','HU','HUN');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('82','Iceland','IS','ISL');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('83','India','IN','IND');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('84','Iran (Islamic Republic of)','IR','IRN');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('85','Israel','IL','ISR');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('86','Italy','IT','ITA');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('88','Iraq','IQ','IRQ');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('89','Japan','JP','JPN');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('90','Jamaica','JM','JAM');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('91','Jordan','JO','JOR');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('92','Kenya','KE','KEN');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('93','Kyrgyzstan','KG','KGZ');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('95','Kiribati','KI','KIR');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('96','Korea, Republic of','KR','KOR');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('97','Kuwait','KW','KWT');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('98','Kazakhstan','KZ','KAZ');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('100','Lebanon','LB','LBN');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('101','Latvia','LV','LVA');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('102','Belarus','BY','BLR');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('103','Lithuania','LT','LTU');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('104','Liberia','LR','LBR');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('105','Slovakia','SK','SVK');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('106','Liechtenstein','LI','LIE');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('107','Libyan Arab Jamahiriya','LY','LBY');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('108','Madagascar','MG','MDG');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('109','Martinique','MQ','MTQ');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('110','Mongolia','MN','MNG');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('111','Montserrat','MS','MSR');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('112','The former Yugoslav Republic of Macedonia','MK','MKD');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('113','Mali','ML','MLI');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('114','Morocco','MA','MAR');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('115','Mauritius','MU','MUS');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('116','Mauritania','MR','MRT');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('117','Malta','MT','MLT');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('118','Oman','OM','OMN');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('119','Maldives','MV','MDV');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('120','Mexico','MX','MEX');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('121','Malaysia','MY','MYS');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('122','Mozambique','MZ','MOZ');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('123','Malawi','MW','MWI');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('124','New Caledonia','NC','NCL');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('125','Niue','NU','NIU');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('126','Niger','NE','NER');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('127','Aruba','AW','ABW');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('128','Anguilla','AI','AIA');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('129','Belgium','BE','BEL');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('130','Hong Kong','HK','HKG');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('131','Northern Mariana Islands','MP','MNP');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('132','Faroe Islands','FO','FRO');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('133','Andorra','AD','AND');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('134','Gibraltar','GI','GIB');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('135','Isle of Man','IM','IMN');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('136','Luxembourg','LU','LUX');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('137','Macau','MO','MAC');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('138','Monaco','MC','MCO');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('139','Palestine','PS','PSE');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('140','Montenegro','ME','MNE');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('141','Mayotte','YT','MYT');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('142','land Islands','AX','ALA');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('143','Norfolk Island','NF','NFK');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('144','Cocos (Keeling) Islands','CC','CCK');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('145','Antarctica','AQ','ATA');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('146','Bouvet Island','BV','BVT');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('147','French Southern and Antarctic Lands','TF','ATF');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('148','Heard Island and McDonald Islands','HM','HMD');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('149','British Indian Ocean Territory','IO','IOT');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('150','Christmas Island','CX','CXR');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('151','United States Minor Outlying Islands','UM','UMI');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('152','Vanuatu','VU','VUT');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('153','Nigeria','NG','NGA');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('154','Netherlands','NL','NLD');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('155','Norway','NO','NOR');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('156','Nepal','NP','NPL');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('157','Nauru','NR','NRU');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('158','Suriname','SR','SUR');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('159','Nicaragua','NI','NIC');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('160','New Zealand','NZ','NZL');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('161','Paraguay','PY','PRY');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('162','Peru','PE','PER');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('163','Pakistan','PK','PAK');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('164','Poland','PL','POL');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('165','Panama','PA','PAN');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('166','Portugal','PT','PRT');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('167','Papua New Guinea','PG','PNG');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('168','Guinea-Bissau','GW','GNB');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('169','Qatar','QA','QAT');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('170','Reunion','RE','REU');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('171','Romania','RO','ROU');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('172','Republic of Moldova','MD','MDA');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('173','Philippines','PH','PHL');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('174','Puerto Rico','PR','PRI');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('175','Russia','RU','RUS');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('176','Rwanda','RW','RWA');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('177','Saudi Arabia','SA','SAU');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('178','Saint Kitts and Nevis','KN','KNA');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('179','Seychelles','SC','SYC');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('180','South Africa','ZA','ZAF');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('181','Lesotho','LS','LSO');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('182','Botswana','BW','BWA');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('183','Senegal','SN','SEN');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('184','Slovenia','SI','SVN');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('185','Sierra Leone','SL','SLE');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('186','Singapore','SG','SGP');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('187','Somalia','SO','SOM');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('188','Spain','ES','ESP');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('189','Saint Lucia','LC','LCA');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('190','Sudan','SD','SDN');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('191','Sweden','SE','SWE');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('192','Syrian Arab Republic','SY','SYR');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('193','Switzerland','CH','CHE');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('194','Trinidad and Tobago','TT','TTO');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('195','Thailand','TH','THA');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('196','Tajikistan','TJ','TJK');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('197','Tokelau','TK','TKL');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('198','Tonga','TO','TON');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('199','Togo','TG','TGO');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('200','Sao Tome and Principe','ST','STP');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('201','Tunisia','TN','TUN');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('202','Turkey','TR','TUR');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('203','Tuvalu','TV','TUV');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('204','Turkmenistan','TM','TKM');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('205','United Republic of Tanzania','TZ','TZA');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('206','Uganda','UG','UGA');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('207','United Kingdom','GB','GBR');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('208','Ukraine','UA','UKR');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('209','United States','US','USA');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('210','Burkina Faso','BF','BFA');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('211','Uruguay','UY','URY');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('212','Uzbekistan','UZ','UZB');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('213','Saint Vincent and the Grenadines','VC','VCT');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('214','Venezuela','VE','VEN');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('215','British Virgin Islands','VG','VGB');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('216','Viet Nam','VN','VNM');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('217','United States Virgin Islands','VI','VIR');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('218','Namibia','NA','NAM');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('219','Wallis and Futuna Islands','WF','WLF');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('220','Samoa','WS','WSM');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('221','Swaziland','SZ','SWZ');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('222','Yemen','YE','YEM');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('223','Zambia','ZM','ZMB');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('224','Zimbabwe','ZW','ZWE');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('225','Indonesia','ID','IDN');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('226','Guadeloupe','GP','GLP');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('227','Netherlands Antilles','AN','ANT');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('228','Untied Arab Emirates','AE','ARE');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('229','Timor-Leste','TL','TLS');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('230','Pitcairn Islands','PN','PCN');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('231','Palau','PW','PLW');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('232','Marshall Islands','MH','MHL');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('233','Saint Pierre and Miquelon','PM','SPM');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('234','Saint Helena','SH','SHN');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('235','San Marino','SM','SMR');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('236','Turks and Caicos Islands','TC','TCA');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('237','Western Sahara','EH','ESH');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('238','Serbia','RS','SRB');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('239','Holy See (Vatican City)','VA','VAT');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('240','Svalbard','SJ','SJM');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('241','Saint Martin','MF','MAF');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('242','Saint Barthelemy','BL','BLM');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('243','Guernsey','GG','GGY');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('244','Jersey','JE','JEY');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('245','South Georgia South Sandwich Islands','GS','SGS');
insert into `wp_donations_countries` (`id`, `name`, `iso_2`, `iso_3`) values('246','Taiwan','TW','TWN');
